### ISSUE TITLE
Unable to create Artista or Obereros via menu

### ISSUE THREAD

**Issue by ArodSnaux** [Taludas/WholesomeHaciendaHaul#14]
Love the mod, but there is one problem if you try to opt out of the mustbeupgraded change (to me the whole point of a hacienda is being able to skip resident upgrades, its like a master planned community)

If you remove residencesmustbeupgraded from the module, there is no way to generate Oberero or Artista homes in the world because these are not present in haciendaseparatebuildmenu. BUT if you remove hacienda separatebuildmenu as well, there is no way to create many of the farms, for example spices, because other changes in the mod have removed them from the vanilla menu (or rather the vanilla recipe books).

Current workaround is to uninstall the mod, manually create an oberero and and artista home, and reinstall the mod with the new menu, but minus the mustbeupgraded module. This is... tedious. Can you please look into this? Thanks!

**Comment by ArodSnaux** [comment]
I think all that is needed here is a patch to the custom menu allowing oberera and artista buildings to be made, if the user has mustbeupgraded installed they will just default to jornalero anyways.

**Comment by Taludas** [comment]
Hi, thanks for your Report! Indeed this is a problem. But it will be solved, once the Modloader supports include skips in the official version. Then I plan to redesign the toggle features to include whole mods. It will resolve by then. For now I'll see, should be an easy fix tbh, but have to see when I find the time.
I have this issue open, so I can remember it :)

**Comment by ArodSnaux** [comment]
Actually I did find a simpler workaround... if you click on the Hacienda, its popup window appears and clicking on the hacienda icon in that window will pop up a window showing all valid options as it bypasses the custom menu logic. So its livable =)

**Comment by Taludas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adapt mod for iMYA Tweaking after GU17 with include skips](https://trello.com/c/QqrffU67/17-adapt-mod-for-imya-tweaking-after-gu17-with-include-skips)

**Comment by Taludas** [comment]
As far as I understand your problem correctly, I don't intend on fixing this problem. So what you need, is the Obrero and Artista Residence inside the separate buildmenu I created, when you don't use the module "residents must be upgraded", correct? I could have a look in that, have a modop that adds them and if you use the mentioned mod, it removes it again.

**Comment by Taludas** [comment]
fixed with v2.2.0
