### ISSUE TITLE
Hacienda Haul not working after SessionBackup (?)

### ISSUE THREAD

**Issue by BrickBob2023** [Taludas/WholesomeHaciendaHaul#15]
Hi, sorry to bother you, I just started to use Anno with Mods and I found your beautiful Mods :-) So far, they worked great and I really enjoyed playing anno again :-) Yesterday everything worked fine and I built the chewing gum factory right before I ended my session.   For some reason, I just ran into an issue: 

After starting the game today, apparently the mod is partially turned off while it is still turned on (and active) in IModYouAnno Manager. The separate building menu (and some of the icons) are still active, but the winery, the additional needs for the obreros and the hacienda versions of the church/firestation/... are gone. The fertilizer must be placed inside the radius again and I cannot upgrade the residents anymore (though, I can build the Obrero residents via the "old" building menu of the Hacienda itself). As far as I can observe, except for the  building menu, all changes due to the mod are gone.

I had this issue one or two times before, but a restart of the game and reload of the savegame fixed the issues. However, yesterday appeared a new (automatically generated?) savegame called "SessionBackup". Since then, I wasn't able to bring the Hacienda Haul back to work. I already tried updating via IMYA/disabling and reload/enabling - reload. The odd savegame is the only difference I could spot for now. Even loading old savegames don't make a change. All other mods from IMYA are working fine.

Is there anything else I can try?

**Comment by Taludas** [comment]
So, it sounds like somehow your tweaking in iMYA messed up the mod en large. Please follow these instructions to get back to vanilla grounds, at least in terms of module activation:

1. Go to the folder Anno 1800/.imya/tweaks/ and look for the imya tweaking backup .json file called something like "[Addon] Hacienda Overhaul (Taludas).json" or "[Overhaul] Hacienda Overhaul.json" if you already used and tweaked the old version. Delete these files.
2. Go to the /mods folder and into the Hacienda Overhauls mod folder. There follow the path data/config/export/main/asset/assets.xml and open it in editor/notepad/vscode etc. The whole document should not have any Skip attributes on the <include> Modops. If you find anything like Skip="1", delete it. If the whole asset file is clear of those, all mod modules should be active again. Save and check a savegame again. The build menu should have the additional entries back.

Hope this solves your issue, ohterwise let me know and I see how to fix it. Deleting the forementioned .json files from iMYA in Step 1 and redownloading the mod should also give good results.

**Comment by BrickBob2023** [comment]
Thank you very much for the quick response! Indeed there were those Skip attributes in the assets.xml. Everything is working fine now ! :-)
