### ISSUE TITLE
Bug with Production Works from Kurila

### ISSUE THREAD

**Issue by dcoolArne** [Taludas/WholesomeHaciendaHaul#17]
If you use Production Works and Hacienda Overhall the new recipes for Schnapps and Beer are included in the Hacienda breweries. But if you chose them from the build menu the version with glass doesn't cost any bricks. You can then change the recipe and delet the brewerie for free bricks.

**Comment by Taludas** [comment]
Hi, this is on Kurilas site to fix since he piggy backs onto my mod. I already gave him a nutch to implement a fix, he now copies the building material cost for the new Hacienda Breweries from my mod directly.
