### ISSUE TITLE
Schnapps Distillery Recipe is Not Present

### ISSUE THREAD

**Issue by Recon419A** [Taludas/WholesomeHaciendaHaul#19]
With my current set of mods, Schnapps does not show up as a recipe option in the Hacienda Brewery. I'm not versed enough in Anno 1800 modding to troubleshoot this further on my own.

Of my ~260 mods, these are the ones that seem like they might touch Haciendas or Schnapps, although I'm guessing you integration test everything you author, so an interaction with Jakob or Kurila might be to blame:
- New World Tourism
- Jakob's New World Cities
- Colossus of the New World
- New World Expanded
- Commuter pier for the new world
- New World Docklands
- Early Game (Kurila)
- Industrial Low Tier Production (Kurila)

**Comment by Taludas** [comment]
Answer from Kurila:
"When Jakobs mod enables the production of glass in the new world, Beer and Schnapps now have their own recipe lists. The breweries should be listed in the Hacienda [build] menu."
![image-2](https://github.com/Taludas/WholesomeHaciendaHaul/assets/64583643/26f294ff-f7cd-4ec0-b02c-2e2aefc8bfd8)

**Comment by Recon419A** [comment]
Sure enough. The red herring in this case is that those modules aren't shown in the Hacienda interface - only the build menu.
![Screenshot 2024-05-25 111051](https://github.com/Taludas/WholesomeHaciendaHaul/assets/16583234/ad6941b2-a530-4de5-9f01-bbcbf3ba4cf3)
