### ISSUE TITLE
Update 16 seems to crash save files with wholesome hacienda mod

### ISSUE THREAD

**Issue by githubber112** [Taludas/WholesomeHaciendaHaul#7]
Hey, I love your mod and I run it in every game I start. 

I noticed since the last update that my game keeps crashing when I load a previous save. I've isolated it to this mod, as I can get the save to load and run if I remove it. Even if I re-add the mod after upgrading my save to include the newest DLC, the game continues to crash. 

I know you probably know about it but I just wanted to bring it to your attention since I love using your mod and it pains me to not have it on.

**Comment by Sheepdog2142** [comment]
I am also getting this issue

**Comment by Taludas** [comment]
Hi,I am aware of the current issues with Hacienda Overhaul breaking your saves and crashing the game. I know the cause of the problems, but as I plan to integrate new features with the next release as well like advanced Hacienda Institutions (Fire station, police, hospital) and new 2*3 Artista residences, the release is delayed. Hopefully I can finish the update within the current week. Remember, I do this in my freetime only and maintaining such a big mid takes quite a while.
 
 
  On Sun, 11 Dec 2022 at 19:20, ***@***.***> wrote:   


I am also getting this issue

**Comment by githubber112** [comment]
Thank you for making this mod! Didn't mean to pressure you, just wanted to point it out in case you didn't know. 

Please take your time updating it. Your mod is amazing!

**Comment by Canderous1989** [comment]
Hope the update will be ready soon (no pressure). Can wait to start me new playthrough with it
