### ISSUE TITLE
Fertiliser works doesn't seem to work outside of hacienda. 

### ISSUE THREAD

**Issue by swedsesn** [Taludas/WholesomeHaciendaHaul#9]
As the title says. I have the FertiliserWorks_IsHaciendaDependent set to false.
When the fertiliser works is placed outside of the hacienda radius it doesn't make the farms around produce dung.

**Comment by Taludas** [comment]
Have you used iModYourAnno? If yes, place destroy existing Fertiliser works and rebuild. Somehow this toggle is not savegame compatible on my machine :(
 
 
  On Tue, 20 Dec 2022 at 22:04, ***@***.***> wrote:   


As the title says. I have the FertiliserWorks_IsHaciendaDependent set to false.
When the fertiliser works is placed outside of the hacienda radius it doesn't make the farms around produce dung.

**Comment by swedsesn** [comment]
I use iModYourAnno and I've tried to replace the Fertiliser works multiple times. At first it doesn't find a warehouse and then it shows missing ingredient.

**Comment by Taludas** [comment]
Have you also tried to toggle the switch on, then save, then toggle it off in IMYA and save again?
 
 
  On Tue, 20 Dec 2022 at 22:24, ***@***.***> wrote:   


I use iModYourAnno and I've tried to replace the Fertiliser works multiple times. At first it doesn't find a warehouse and then it shows missing ingredient.

**Comment by swedsesn** [comment]
That solved the issue! Thank you :)
